#!/usr/bin/env python3
"""
Collect D435 depth values for AI Camera ROI boxes.

Development-only calibration/measurement utility.

Input:
- ROI CSV generated by set_kp_imx.py:
  timestamp,roi,x1,y1,x2,y2,cx,cy,confidence

Output:
- Per-body-part depth values from the D435 depth frame.

Mapping:
- Default: scale AI Camera coordinates to D435 depth frame size.
- Optional: apply AI->Depth homography JSON when calibration is available.
"""

from __future__ import annotations

import argparse
import csv
import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np

try:
    import pyrealsense2 as rs
except ImportError as exc:
    raise SystemExit(
        "pyrealsense2 is not installed. Install Intel RealSense SDK/python binding first."
    ) from exc


@dataclass
class RoiBox:
    timestamp: float
    name: str
    x1: float
    y1: float
    x2: float
    y2: float
    cx: float
    cy: float
    confidence: float


@dataclass
class DepthMeasurement:
    timestamp: float
    roi_timestamp: float
    roi: str
    x1: int
    y1: int
    x2: int
    y2: int
    cx: int
    cy: int
    sample_size: int
    confidence: float
    valid_ratio: float
    center_m: Optional[float]
    median_m: Optional[float]
    mean_m: Optional[float]
    min_m: Optional[float]
    max_m: Optional[float]
    posture_state: str = "baseline_pending"
    posture_reason: str = "baseline_pending"
    posture_alarm: bool = False
    posture_elapsed_seconds: float = 0.0
    head_delta_m: Optional[float] = None
    shoulder_delta_m: Optional[float] = None
    chest_delta_m: Optional[float] = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Collect D435 depth by AI Camera ROI boxes")
    parser.add_argument("--roi-csv", type=Path, default=Path("kp_roi_log.csv"))
    parser.add_argument("--output-csv", type=Path, default=Path("roi_depth_log.csv"))
    parser.add_argument("--homography", type=Path, help="Optional JSON containing H_ai_to_depth")
    parser.add_argument("--ai-width", type=int, default=640)
    parser.add_argument("--ai-height", type=int, default=480)
    parser.add_argument("--depth-width", type=int, default=640)
    parser.add_argument("--depth-height", type=int, default=480)
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument("--seconds", type=float, default=0.0, help="0 means run until Ctrl+C")
    parser.add_argument("--poll-interval", type=float, default=0.2)
    parser.add_argument("--min-confidence", type=float, default=0.30)
    parser.add_argument("--min-depth-m", type=float, default=0.15)
    parser.add_argument("--max-depth-m", type=float, default=3.0)
    parser.add_argument("--head-depth-roi-size", type=int, default=40)
    parser.add_argument("--body-depth-roi-size", type=int, default=60)
    parser.add_argument("--baseline-seconds", type=float, default=5.0)
    parser.add_argument("--bad-duration-seconds", type=float, default=5.0)
    parser.add_argument("--head-depth-threshold-m", type=float, default=0.07)
    parser.add_argument("--torso-depth-threshold-m", type=float, default=0.035)
    parser.add_argument("--torso-stable-threshold-m", type=float, default=0.015)
    parser.add_argument("--shoulder-tilt-threshold-px", type=float, default=25.0)
    parser.add_argument(
        "--required-rois",
        default="head,shoulder,chest",
        help="Comma-separated ROI names that must exist in the same timestamp group",
    )
    return parser.parse_args()


class PostureDetector:
    def __init__(self, args: argparse.Namespace) -> None:
        self.args = args
        self.baseline_started_at: Optional[float] = None
        self.baseline_depths: Dict[str, List[float]] = {"head": [], "shoulder": [], "chest": []}
        self.baseline_centers_y: Dict[str, List[float]] = {"shoulder": []}
        self.baseline_depth: Optional[Dict[str, float]] = None
        self.baseline_shoulder_y: Optional[float] = None
        self.bad_since: Optional[float] = None
        self.last_state = "baseline_pending"

    def analyze(self, measurements: List[DepthMeasurement]) -> Tuple[str, str, bool, float, Dict[str, Optional[float]]]:
        now = time.time()
        by_roi = {measurement.roi: measurement for measurement in measurements}
        required = ("head", "shoulder", "chest")
        if any(name not in by_roi or by_roi[name].median_m is None for name in required):
            self.bad_since = None
            return "unknown", "missing_depth_measurement", False, 0.0, {}

        if self.baseline_depth is None:
            if self.baseline_started_at is None:
                self.baseline_started_at = now
            for name in required:
                self.baseline_depths[name].append(float(by_roi[name].median_m))
            self.baseline_centers_y["shoulder"].append(float(by_roi["shoulder"].cy))

            elapsed = now - self.baseline_started_at
            if elapsed >= self.args.baseline_seconds:
                self.baseline_depth = {
                    name: float(np.median(values))
                    for name, values in self.baseline_depths.items()
                    if values
                }
                self.baseline_shoulder_y = float(np.median(self.baseline_centers_y["shoulder"]))
                print(f"Depth baseline recorded: {self.baseline_depth}", flush=True)
            return "baseline_pending", "recording_depth_baseline", False, 0.0, {}

        deltas = {
            name: self.baseline_depth[name] - float(by_roi[name].median_m)
            for name in required
        }
        shoulder_y_delta = abs(float(by_roi["shoulder"].cy) - float(self.baseline_shoulder_y or by_roi["shoulder"].cy))
        reason = self._classify(deltas, shoulder_y_delta)

        if reason == "normal":
            self.bad_since = None
            self.last_state = "normal"
            return "normal", "normal", False, 0.0, deltas

        if self.bad_since is None or self.last_state != reason:
            self.bad_since = now
        self.last_state = reason
        elapsed = max(0.0, now - self.bad_since)
        return "bad", reason, elapsed >= self.args.bad_duration_seconds, elapsed, deltas

    def _classify(self, deltas: Dict[str, float], shoulder_y_delta: float) -> str:
        head = deltas["head"]
        shoulder = deltas["shoulder"]
        chest = deltas["chest"]

        if shoulder_y_delta >= self.args.shoulder_tilt_threshold_px:
            return "shoulder_tilt"
        if head >= self.args.head_depth_threshold_m and shoulder >= self.args.torso_depth_threshold_m:
            return "forward_lean"
        if (
            head >= self.args.head_depth_threshold_m
            and abs(shoulder) <= self.args.torso_stable_threshold_m
        ):
            return "turtle_neck"
        return "normal"


def load_homography(path: Optional[Path]) -> Optional[np.ndarray]:
    if path is None:
        return None
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    matrix = data.get("H_ai_to_depth") or data.get("homography") or data.get("matrix")
    if matrix is None:
        raise ValueError(f"{path} does not contain H_ai_to_depth/homography/matrix")
    h = np.asarray(matrix, dtype=np.float32)
    if h.shape != (3, 3):
        raise ValueError(f"homography matrix must be 3x3, got {h.shape}")
    return h


def read_latest_roi_group(path: Path, min_confidence: float, required_rois: List[str]) -> List[RoiBox]:
    if not path.exists():
        return []

    groups: Dict[float, Dict[str, RoiBox]] = {}

    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                roi = RoiBox(
                    timestamp=float(row["timestamp"]),
                    name=row["roi"],
                    x1=float(row["x1"]),
                    y1=float(row["y1"]),
                    x2=float(row["x2"]),
                    y2=float(row["y2"]),
                    cx=float(row["cx"]),
                    cy=float(row["cy"]),
                    confidence=float(row["confidence"]),
                )
            except (KeyError, TypeError, ValueError):
                continue

            if roi.confidence < min_confidence:
                continue

            groups.setdefault(roi.timestamp, {})[roi.name] = roi

    for timestamp in sorted(groups.keys(), reverse=True):
        group = groups[timestamp]
        if set(required_rois).issubset(group.keys()):
            return [group[name] for name in required_rois]

    return []


def transform_points(points: np.ndarray, homography: Optional[np.ndarray], scale_x: float, scale_y: float) -> np.ndarray:
    if homography is None:
        mapped = points.copy().astype(np.float32)
        mapped[:, 0] *= scale_x
        mapped[:, 1] *= scale_y
        return mapped

    ones = np.ones((points.shape[0], 1), dtype=np.float32)
    homogeneous = np.concatenate([points.astype(np.float32), ones], axis=1)
    projected = homogeneous @ homography.T
    projected[:, 0] /= projected[:, 2]
    projected[:, 1] /= projected[:, 2]
    return projected[:, :2]


def map_roi_to_depth(
    roi: RoiBox,
    homography: Optional[np.ndarray],
    ai_width: int,
    ai_height: int,
    depth_width: int,
    depth_height: int,
    sample_size: int,
) -> Tuple[int, int, int, int, int, int]:
    scale_x = depth_width / ai_width
    scale_y = depth_height / ai_height
    points = np.asarray([[roi.cx, roi.cy]], dtype=np.float32)
    mapped = transform_points(points, homography, scale_x, scale_y)

    cx = int(np.clip(round(mapped[0, 0]), 0, depth_width - 1))
    cy = int(np.clip(round(mapped[0, 1]), 0, depth_height - 1))
    half = max(1, sample_size // 2)
    x1 = int(np.clip(cx - half, 0, depth_width - 1))
    x2 = int(np.clip(cx + half, 0, depth_width - 1))
    y1 = int(np.clip(cy - half, 0, depth_height - 1))
    y2 = int(np.clip(cy + half, 0, depth_height - 1))

    if x2 <= x1:
        x2 = min(depth_width - 1, x1 + 1)
    if y2 <= y1:
        y2 = min(depth_height - 1, y1 + 1)

    return x1, y1, x2, y2, cx, cy


def measure_depth(
    depth_m: np.ndarray,
    roi: RoiBox,
    mapped_box: Tuple[int, int, int, int, int, int],
    sample_size: int,
    min_depth_m: float,
    max_depth_m: float,
) -> DepthMeasurement:
    x1, y1, x2, y2, cx, cy = mapped_box
    crop = depth_m[y1 : y2 + 1, x1 : x2 + 1]
    valid = crop[(crop >= min_depth_m) & (crop <= max_depth_m)]
    center = float(depth_m[cy, cx])
    center_m = center if min_depth_m <= center <= max_depth_m else None

    return DepthMeasurement(
        timestamp=time.time(),
        roi_timestamp=roi.timestamp,
        roi=roi.name,
        x1=x1,
        y1=y1,
        x2=x2,
        y2=y2,
        cx=cx,
        cy=cy,
        sample_size=sample_size,
        confidence=roi.confidence,
        valid_ratio=float(valid.size / crop.size) if crop.size else 0.0,
        center_m=center_m,
        median_m=float(np.median(valid)) if valid.size else None,
        mean_m=float(np.mean(valid)) if valid.size else None,
        min_m=float(np.min(valid)) if valid.size else None,
        max_m=float(np.max(valid)) if valid.size else None,
    )


def format_meters(value: Optional[float]) -> str:
    if value is None:
        return "invalid"
    return f"{value:.3f}m"


def open_output(path: Path):
    f = path.open("w", newline="", encoding="utf-8")
    writer = csv.writer(f)
    writer.writerow(
        [
            "timestamp",
            "roi_timestamp",
            "roi",
            "x1",
            "y1",
            "x2",
            "y2",
            "cx",
            "cy",
            "sample_size",
            "confidence",
            "valid_ratio",
            "center_m",
            "median_m",
            "mean_m",
            "min_m",
            "max_m",
            "posture_state",
            "posture_reason",
            "posture_alarm",
            "posture_elapsed_seconds",
            "head_delta_m",
            "shoulder_delta_m",
            "chest_delta_m",
        ]
    )
    f.flush()
    return f, writer


def write_measurements(writer: csv.writer, measurements: Iterable[DepthMeasurement]) -> None:
    for m in measurements:
        writer.writerow(
            [
                m.timestamp,
                m.roi_timestamp,
                m.roi,
                m.x1,
                m.y1,
                m.x2,
                m.y2,
                m.cx,
                m.cy,
                m.sample_size,
                f"{m.confidence:.3f}",
                f"{m.valid_ratio:.3f}",
                "" if m.center_m is None else f"{m.center_m:.4f}",
                "" if m.median_m is None else f"{m.median_m:.4f}",
                "" if m.mean_m is None else f"{m.mean_m:.4f}",
                "" if m.min_m is None else f"{m.min_m:.4f}",
                "" if m.max_m is None else f"{m.max_m:.4f}",
                m.posture_state,
                m.posture_reason,
                int(m.posture_alarm),
                f"{m.posture_elapsed_seconds:.3f}",
                "" if m.head_delta_m is None else f"{m.head_delta_m:.4f}",
                "" if m.shoulder_delta_m is None else f"{m.shoulder_delta_m:.4f}",
                "" if m.chest_delta_m is None else f"{m.chest_delta_m:.4f}",
            ]
        )


def print_measurements(measurements: List[DepthMeasurement]) -> None:
    if not measurements:
        print("depth_by_roi: no valid ROI", flush=True)
        return
    parts = [
        f"{m.roi}=median:{format_meters(m.median_m)} center:{format_meters(m.center_m)} valid:{m.valid_ratio * 100:.0f}%"
        for m in measurements
    ]
    posture = measurements[0].posture_reason if measurements else "unknown"
    alarm = measurements[0].posture_alarm if measurements else False
    print("depth_by_roi: " + " | ".join(parts) + f" | posture={posture} alarm={alarm}", flush=True)


def main() -> None:
    args = parse_args()
    homography = load_homography(args.homography)
    if homography is None:
        print("Mapping mode: scaled AI coordinates -> depth coordinates")
    else:
        print(f"Mapping mode: homography {args.homography}")

    pipeline = rs.pipeline()
    config = rs.config()
    config.enable_stream(rs.stream.depth, args.depth_width, args.depth_height, rs.format.z16, args.fps)

    print(f"Starting D435 depth stream: {args.depth_width}x{args.depth_height}@{args.fps}")
    profile = pipeline.start(config)
    depth_scale = profile.get_device().first_depth_sensor().get_depth_scale()
    print(f"Depth scale: {depth_scale}")

    output_file, writer = open_output(args.output_csv)
    required_rois = [name.strip() for name in args.required_rois.split(",") if name.strip()]
    posture_detector = PostureDetector(args)
    start = time.time()
    rows_written = 0

    try:
        while args.seconds <= 0 or time.time() - start < args.seconds:
            roi_boxes = read_latest_roi_group(args.roi_csv, args.min_confidence, required_rois)
            frames = pipeline.wait_for_frames(timeout_ms=5000)
            depth_frame = frames.get_depth_frame()
            if not depth_frame:
                print("No depth frame", flush=True)
                time.sleep(args.poll_interval)
                continue

            depth_raw = np.asanyarray(depth_frame.get_data())
            depth_m = depth_raw.astype(np.float32) * depth_scale

            measurements: List[DepthMeasurement] = []
            for roi in roi_boxes:
                sample_size = args.head_depth_roi_size if roi.name == "head" else args.body_depth_roi_size
                mapped = map_roi_to_depth(
                    roi,
                    homography,
                    args.ai_width,
                    args.ai_height,
                    args.depth_width,
                    args.depth_height,
                    sample_size,
                )
                measurements.append(
                    measure_depth(depth_m, roi, mapped, sample_size, args.min_depth_m, args.max_depth_m)
                )

            state, reason, alarm, elapsed, deltas = posture_detector.analyze(measurements)
            for measurement in measurements:
                measurement.posture_state = state
                measurement.posture_reason = reason
                measurement.posture_alarm = alarm
                measurement.posture_elapsed_seconds = elapsed
                measurement.head_delta_m = deltas.get("head")
                measurement.shoulder_delta_m = deltas.get("shoulder")
                measurement.chest_delta_m = deltas.get("chest")

            write_measurements(writer, measurements)
            output_file.flush()
            rows_written += len(measurements)
            print_measurements(measurements)
            time.sleep(args.poll_interval)
    except KeyboardInterrupt:
        print("\nStopping ROI depth collector.")
    finally:
        output_file.flush()
        output_file.close()
        pipeline.stop()
        print(f"Depth ROI log saved to {args.output_csv} ({rows_written} rows)")


if __name__ == "__main__":
    main()
